  
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dsmsreviewapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dsmsreviewapp 
    spec:
      containers:
        - name: dsmsreviewapp 
          image: dsmsacr.azurecr.io/my-image
          ports:
          - containerPort: 80
