  
apiVersion : apps/v1
kind: Deployment
metadata:
  name: dsmsreviewapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dsmsreviewapp 
    spec:
      containers:
        - name: dsmsreviewapp 
          image: dsmsacr.azurecr.io/myimage
          ports:
          - containerPort: 80
